// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://<<ANONYMIZED>>.appsync-api.eu-central-1.amazonaws.com/graphql',
          region: 'eu-central-1',
          defaultAuthMode: 'userPool',
        }
    }
};

export default config;